### ISSUE TITLE
Question: Can this detect links/hashtags/mentions while the user is editing the text?

### ISSUE THREAD

**Issue by mitchellporter** [fsjack/JKRichTextView#1]
Just a quick question.

Will this highlight links, hashtags, and @ mentions as the user is editing the textview and typing, realtime?

Thanks.

**Comment by fsjack** [comment]
I just update the repo. 
it can support detecting links realtime now by enabling textView's shouldAutoDetectDataWhileEditing (Actually you dont need to do anything because it's YES by default).

Remember if your text view is editable, you must set shouldPassthoughUntouchableText as NO otherwise you cannot edit your text view normally. 

One more thing is even the links could be detected, the link would not able be click 'cause the text view is under edit mode.

Still under test, I will push it to CocoaPods when it's stable. Use on your own risk.

**Comment by fsjack** [comment]
I just make shouldPassthoughUntouchableText NO by default in case of confusion.

**Comment by mitchellporter** [comment]
@fsjack Hey Jackie, thanks for taking the time to do that! I really appreciate it. I will set this up and test it tomorrow and let you know if I have any trouble. If I hit any roadblocks I'd be happy to contribute too so we can get this feature pushed out to cocoapods as fast as possible.

**Comment by fsjack** [comment]
@mitchellporter thank you so much. just feel free to send pull request :)

**Comment by mitchellporter** [comment]
@fsjack I'm looking at the demo and it looks like you have to set a string to detect and highlight like "#github", but how can I make it so that any word that starts with # or @ is detected/highlighted?

**Comment by mitchellporter** [comment]
@fsjack Another update, I'm setting shouldAutoDetectDataWhileEditing  to YES and shouldPassthoughUntouchableText to NO and can't seem to figure this out. 

Jackie, did you test this real quick before pushing the update? If you did and it detected links, hashtags, and @ mentions realtime while editing would you be willing to share that code with me?

Thanks.

**Comment by fsjack** [comment]
@mitchellporter my demo have no hashtag link detection so far, you need to implement your own DataDetectionHandler to support hashtag link detection. But the demo do have @name and links detection. Only the 'JKRichTextView' link is set to open alertView in the demo, others are parsed automatically by JKRichTextView.

There're two ways to test. One you could set your own string for the textView like the demo do. another is go to Main storyboard and make the textView editable and then run the demo, then you can input @ mention or any links you want to see the result.

**Comment by mitchellporter** [comment]
@fsjack  thanks again for everything, but I ended up just using a simple method that checks for hashtags and @usernames and highlights from there. Would be happy to share the code if you're interested.

**Comment by fsjack** [comment]
@mitchellporter dont tell me you solve the problem with single line of code.😂

**Comment by mitchellporter** [comment]
@fsjack Haha no it's an entire method and right now it only detects hashtags and username mentions. I still need to add support for URL's.
